# Site settings
title: Prabal Sikder
name: Prabal Kanti Deb Sikder
nickname: "(Probal Sikder)"
description: "<p>
Software engineer with 15+ years of experience designing and implementing large enterprise applications in 
<br />Java, Springboot, Kafka, Golang, Terraform, Kubernetes, AWS, and Azure cloud,  
<br />with expertise in microservices, distributed systems, and cloud computing.
</p>
url: ""


github_username:  probal
linkedin_username: probalsikder
email: probalsikder@gmail.com
short_resume_gdrive_url: "https://drive.google.com/file/d/1FqlxKj2Y8BTYaA_nj6j4RO2Yvmeevhtd/view"
resume_gdrive_url: "https://drive.google.com/file/d/1zqwH-WbC63QAvarJqt21283eBcM8bmi7/view"
scrum_certificate: "https://drive.google.com/file/d/1J0r4CAFs1qs5dDrHYKRDFeIEqmwRfVdP/view"

avatar: yes
avatar_img_path: "imgs/probal.png"


front_img: yes
front_img_path: "imgs/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
