# Site settings
name: Prabal Kanti Deb Sikder
description: "<p>
A software developer with more than 11 years of well-rounded industry experience.
<br />Mostly focused on web developmenet in java ecosystem.
</p>
<p>
<br />
</p>"
url: ""


github_username:  probal
linked_in_username: probalsikder
email: probalsikder@gmail.com
resume_gdrive_url: "https://drive.google.com/file/d/1kM-0FZmYXFJPWASCubjPsCBJXvA79KfG/view?usp=sharing"

avatar: yes
avatar_img_path: "imgs/probal.png"


front_img: yes
front_img_path: "imgs/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty
