# Site settings
title: Probal Sikder
name: Prabal Kanti Deb Sikder
nickname: "(aka: Probal Sikder)"
description: "<p>
A software developer with more than 15 years of well-rounded industry experience.
<br />Enthusiastic to design and implement large enterprise applications. Eager to learn new technologies.
</p>
<p>
<br />Please follow the links bellow to know more. Cheers!!!
</p>"
url: ""


github_username:  probal
linkedin_username: probalsikder
email: probalsikder@gmail.com
resume_gdrive_url: "https://drive.google.com/drive/folders/1PM_n8NS-ejUXtDQoh8z6CXGRMuexM9ml/view"

avatar: yes
avatar_img_path: "imgs/probal.png"


front_img: yes
front_img_path: "imgs/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
