# Site settings
title: Prabal Sikder
name: Prabal Kanti Deb Sikder
nickname: "(Probal Sikder)"
description: "<p>
I am a software developer with 15+ years of experience in designing and implementing large enterprise applications. 
<br />I am proficient in a wide range of technologies including Java, Golang, Terraform, Kubernetes, AWS and Azure cloud. 
<br />I have a proven track record of success in delivering complex projects on time and on budget.
</p>
<p>
<br />I am currently open for corp-to-corp (C2C) contracts. 
<br>
If you are looking for a Engineer to help you with your next project, please contact me at <a href = "mailto: probalsikder@gmail.com">probalsikder@gmail.com</a>
</br>
</p>"
url: ""


github_username:  probal
linkedin_username: probalsikder
email: probalsikder@gmail.com
short_resume_gdrive_url: "https://drive.google.com/file/d/1FqlxKj2Y8BTYaA_nj6j4RO2Yvmeevhtd/view"
resume_gdrive_url: "https://drive.google.com/file/d/1zqwH-WbC63QAvarJqt21283eBcM8bmi7/view"

avatar: yes
avatar_img_path: "imgs/probal.png"


front_img: yes
front_img_path: "imgs/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
