# Site settings
title: Probal Sikder
name: Prabal Kanti Deb Sikder
nickname: "(aka: Probal Sikder)"
description: "<p>
Hi there!!! I am a software developer with more than 15 years of well-rounded industry experience.
<br />Enthusiastic to design and implement large enterprise applications. Eager to learn new technologies.
</p>
<p>
<br />Open for corp-to-corp (C2C) contracts. Please follow the links bellow to know more. Cheers!!!
</p>"
url: ""


github_username:  probal
linkedin_username: probalsikder
email: probalsikder@gmail.com
resume_gdrive_url: "https://drive.google.com/file/d/1FqlxKj2Y8BTYaA_nj6j4RO2Yvmeevhtd/view"
resume_gdrive_url: "https://drive.google.com/file/d/1zqwH-WbC63QAvarJqt21283eBcM8bmi7/view"

avatar: yes
avatar_img_path: "imgs/probal.png"


front_img: yes
front_img_path: "imgs/background.jpg"

# Build settings
markdown: kramdown
permalink: pretty

plugins:
  - jekyll-seo-tag
